# Generated by Django 3.2.9 on 2022-03-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=50)),
                ('item_img', models.ImageField(upload_to='images/', verbose_name='Item Name')),
                ('item_price', models.IntegerField(default=0)),
                ('item_type', models.CharField(max_length=50)),
            ],
        ),
    ]
