# Generated by Django 3.2.9 on 2022-03-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='item_img',
            field=models.ImageField(upload_to='images/', verbose_name='Item img'),
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='Products',
        ),
    ]
